buildscript {
    ext {
        composeBom = "2026.01.00"
        compile_sdk = 36
        appcompat = "1.7.1"
        target_sdk = 36
        min_sdk = 26
        crashliticsGradle = "3.0.5"
        prefPlugin = "2.0.2"
        androidxCore = "1.16.0"
        lifecycleRuntimeKtx = "2.10.0"
        activityKtx = "1.12.3"
        junit = "4.13.2"
        androidXJunit = "1.3.0"
        espreso = "3.7.0"
        hiltAndroid = "2.57.1"
        firebaseBom = "34.7.0"
        navigation3 = "1.0.0"
        lifecycleNav3 = "2.10.0"
        hiltCompose = "1.3.0"
        kotlinxSerialization = "1.9.0"
        coroutines = "1.10.2"
        googleServices = "4.4.4"
        camera2 = "1.5.3"
        zxing = "3.5.4"
        ksp = "2.3.0"
    }

    repositories {
        maven { url "https://jitpack.io" }
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.google.firebase:firebase-crashlytics-gradle:$crashliticsGradle")
        classpath("com.google.dagger:hilt-android-gradle-plugin:$hiltAndroid")
        classpath("com.google.firebase:perf-plugin:$prefPlugin")
        classpath("com.google.gms:google-services:$googleServices")
    }
}

plugins {
    id("com.android.application") version '9.0.0' apply false
    id("com.android.library") version '9.0.0' apply false
    id("org.jetbrains.kotlin.android") version "2.2.21" apply false
    id("org.jlleitschuh.gradle.ktlint") version "10.2.1"
    id("org.jetbrains.kotlin.plugin.compose") version "2.2.21"
    id("org.jetbrains.kotlin.plugin.serialization") version "2.2.21" apply false
    id("com.google.devtools.ksp") version "2.3.0" apply false
}
