dependencies {

    implementation("androidx.core:core-ktx:$androidxCore")

    // Kotlin

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutines")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-play-services:$coroutines")

    // Lifecycle

    implementation("androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleRuntimeKtx")

    // Activity

    implementation("androidx.activity:activity-compose:$activityKtx")

    // Hilt Compose
    implementation("androidx.hilt:hilt-lifecycle-viewmodel-compose:$hiltCompose")

    // Compose BOM

    def composeBom = platform("androidx.compose:compose-bom:$composeBom")
    implementation(composeBom)
    androidTestImplementation(composeBom)

    // Material

    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")

    // Hilt

    implementation("com.google.dagger:hilt-android:$hiltAndroid")
    ksp("com.google.dagger:hilt-android-compiler:$hiltAndroid")

    // Serialization

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:$kotlinxSerialization")

    // Compose

    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.ui:ui-text-google-fonts")
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")

    implementation("com.valentinilk.shimmer:compose-shimmer:1.3.3")

    implementation("com.github.leonard-palm:compose-state-events:1.2.3")

    // Testing

    testImplementation("junit:junit:$junit")
    androidTestImplementation("androidx.test.ext:junit:$androidXJunit")
    androidTestImplementation("androidx.test.espresso:espresso-core:$espreso")
}
