package com.polo.core.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF526600)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD4ED7E)
val md_theme_light_onPrimaryContainer = Color(0xFF171E00)
val md_theme_light_secondary = Color(0xFFB22D00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBD1)
val md_theme_light_onSecondaryContainer = Color(0xFF3B0900)
val md_theme_light_tertiary = Color(0xFF8C4F00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCBF)
val md_theme_light_onTertiaryContainer = Color(0xFF2D1600)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF3FFFA)
val md_theme_light_onBackground = Color(0xFF00201A)
val md_theme_light_surface = Color(0xFFF3FFFA)
val md_theme_light_onSurface = Color(0xFF00201A)
val md_theme_light_surfaceVariant = Color(0xFFE3E4D3)
val md_theme_light_onSurfaceVariant = Color(0xFF46483C)
val md_theme_light_outline = Color(0xFF77786A)
val md_theme_light_inverseOnSurface = Color(0xFFB7FFEC)
val md_theme_light_inverseSurface = Color(0xFF00382E)
val md_theme_light_inversePrimary = Color(0xFFB8D166)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF526600)
val md_theme_light_outlineVariant = Color(0xFFC7C8B8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB8D166)
val md_theme_dark_onPrimary = Color(0xFF293500)
val md_theme_dark_primaryContainer = Color(0xFF3D4C00)
val md_theme_dark_onPrimaryContainer = Color(0xFFD4ED7E)
val md_theme_dark_secondary = Color(0xFFFFB5A1)
val md_theme_dark_onSecondary = Color(0xFF601400)
val md_theme_dark_secondaryContainer = Color(0xFF882000)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBD1)
val md_theme_dark_tertiary = Color(0xFFFFB874)
val md_theme_dark_onTertiary = Color(0xFF4B2800)
val md_theme_dark_tertiaryContainer = Color(0xFF6B3B00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCBF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00201A)
val md_theme_dark_onBackground = Color(0xFF79F8DC)
val md_theme_dark_surface = Color(0xFF00201A)
val md_theme_dark_onSurface = Color(0xFF79F8DC)
val md_theme_dark_surfaceVariant = Color(0xFF46483C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C8B8)
val md_theme_dark_outline = Color(0xFF909283)
val md_theme_dark_inverseOnSurface = Color(0xFF00201A)
val md_theme_dark_inverseSurface = Color(0xFF79F8DC)
val md_theme_dark_inversePrimary = Color(0xFF526600)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB8D166)
val md_theme_dark_outlineVariant = Color(0xFF46483C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF353531)
