plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}

apply from: rootDir.path + "/common.config.gradle"
apply from: rootDir.path + "/common.dependencies.gradle"

android {
    namespace = 'com.polo.warehouse'
    compileSdk compile_sdk

    defaultConfig {
        applicationId "com.polo.warehouse"
        minSdk min_sdk
        targetSdk target_sdk
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix(".debug")
            debuggable = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        staging {
            applicationIdSuffix(".alpha")
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {

    implementation(platform("com.google.firebase:firebase-bom:$firebaseBom"))
    implementation("com.google.firebase:firebase-crashlytics")
    implementation("com.google.firebase:firebase-analytics")

    implementation("androidx.appcompat:appcompat:$appcompat")
    implementation("androidx.navigation3:navigation3-runtime:$navigation3")
    implementation("androidx.navigation3:navigation3-ui:$navigation3")
    implementation("androidx.lifecycle:lifecycle-viewmodel-navigation3:$lifecycleNav3")

    implementation(project(":libraries:core"))
    implementation(project(":libraries:core-data"))
    implementation(project(":libraries:core-ui"))
    implementation(project(":libraries:domain"))
    implementation(project(":feature:authentication"))
    implementation(project(":feature:dashboard"))
    implementation(project(":feature:pallet"))
    implementation(project(":feature:scanner"))
}
