package com.polo.designsystem.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1A67FF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF00204D)
val md_theme_light_secondary = Color(0xFFE69500)
val md_theme_light_onSecondary = Color(0xFF1A1100)
val md_theme_light_secondaryContainer = Color(0xFFFFE5B3)
val md_theme_light_onSecondaryContainer = Color(0xFF4D3200)
val md_theme_light_tertiary = Color(0xFF0E7490)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCFFAFE)
val md_theme_light_onTertiaryContainer = Color(0xFF164E63)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_errorContainer = Color(0xFFFEE2E2)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF7F1D1D)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF111827)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF111827)
val md_theme_light_surfaceVariant = Color(0xFFF3F4F6)
val md_theme_light_onSurfaceVariant = Color(0xFF4B5563)
val md_theme_light_outline = Color(0xFFD1D5DB)
val md_theme_light_inverseOnSurface = Color(0xFFFFFFFF)
val md_theme_light_inverseSurface = Color(0xFF111827)
val md_theme_light_inversePrimary = Color(0xFFAACCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1A67FF)
val md_theme_light_outlineVariant = Color(0xFFE5E7EB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF7AADFF)
val md_theme_dark_onPrimary = Color(0xFF00204D)
val md_theme_dark_primaryContainer = Color(0xFF0040B3)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_secondary = Color(0xFFFFC44D)
val md_theme_dark_onSecondary = Color(0xFF4D3200)
val md_theme_dark_secondaryContainer = Color(0xFF805300)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE5B3)
val md_theme_dark_tertiary = Color(0xFF67E8F9)
val md_theme_dark_onTertiary = Color(0xFF164E63)
val md_theme_dark_tertiaryContainer = Color(0xFF155E75)
val md_theme_dark_onTertiaryContainer = Color(0xFFCFFAFE)
val md_theme_dark_error = Color(0xFFF87171)
val md_theme_dark_errorContainer = Color(0xFF7F1D1D)
val md_theme_dark_onError = Color(0xFF450A0A)
val md_theme_dark_onErrorContainer = Color(0xFFFEE2E2)
val md_theme_dark_background = Color(0xFF030712)
val md_theme_dark_onBackground = Color(0xFFF9FAFB)
val md_theme_dark_surface = Color(0xFF030712)
val md_theme_dark_onSurface = Color(0xFFF9FAFB)
val md_theme_dark_surfaceVariant = Color(0xFF1F2937)
val md_theme_dark_onSurfaceVariant = Color(0xFF9CA3AF)
val md_theme_dark_outline = Color(0xFF4B5563)
val md_theme_dark_inverseOnSurface = Color(0xFF111827)
val md_theme_dark_inverseSurface = Color(0xFFF9FAFB)
val md_theme_dark_inversePrimary = Color(0xFF1A67FF)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7AADFF)
val md_theme_dark_outlineVariant = Color(0xFF374151)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF1A67FF)
