package com.polo.designsystem.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1A1A1A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFECECEC)
val md_theme_light_onPrimaryContainer = Color(0xFF111111)
val md_theme_light_secondary = Color(0xFF2D2D2D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE6E6E6)
val md_theme_light_onSecondaryContainer = Color(0xFF141414)
val md_theme_light_tertiary = Color(0xFF3A3A3A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE2E2E2)
val md_theme_light_onTertiaryContainer = Color(0xFF151515)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF111111)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF111111)
val md_theme_light_surfaceVariant = Color(0xFFF2F2F2)
val md_theme_light_onSurfaceVariant = Color(0xFF444444)
val md_theme_light_outline = Color(0xFF7A7A7A)
val md_theme_light_inverseOnSurface = Color(0xFFF5F5F5)
val md_theme_light_inverseSurface = Color(0xFF1F1F1F)
val md_theme_light_inversePrimary = Color(0xFFF2F2F2)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1A1A1A)
val md_theme_light_outlineVariant = Color(0xFFD0D0D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFF2F2F2)
val md_theme_dark_onPrimary = Color(0xFF1A1A1A)
val md_theme_dark_primaryContainer = Color(0xFF2A2A2A)
val md_theme_dark_onPrimaryContainer = Color(0xFFF2F2F2)
val md_theme_dark_secondary = Color(0xFFD9D9D9)
val md_theme_dark_onSecondary = Color(0xFF1A1A1A)
val md_theme_dark_secondaryContainer = Color(0xFF323232)
val md_theme_dark_onSecondaryContainer = Color(0xFFEEEEEE)
val md_theme_dark_tertiary = Color(0xFFC8C8C8)
val md_theme_dark_onTertiary = Color(0xFF161616)
val md_theme_dark_tertiaryContainer = Color(0xFF363636)
val md_theme_dark_onTertiaryContainer = Color(0xFFEAEAEA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0F0F10)
val md_theme_dark_onBackground = Color(0xFFF4F4F4)
val md_theme_dark_surface = Color(0xFF0F0F10)
val md_theme_dark_onSurface = Color(0xFFF4F4F4)
val md_theme_dark_surfaceVariant = Color(0xFF2A2A2C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8C8CC)
val md_theme_dark_outline = Color(0xFF909095)
val md_theme_dark_inverseOnSurface = Color(0xFF111111)
val md_theme_dark_inverseSurface = Color(0xFFF4F4F4)
val md_theme_dark_inversePrimary = Color(0xFF1A1A1A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF2F2F2)
val md_theme_dark_outlineVariant = Color(0xFF4A4A4E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF1A1A1A)
